ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".vinoddevops.online
redis_host: redis-"{{ env }}".vinoddevops.online
user_host: user-"{{ env }}".vinoddevops.online
catalogue_host: catalogue-"{{ env }}".vinoddevops.online
cart_host: cart-"{{ env }}".vinoddevops.online
mysql_host: mysql-"{{ env }}".vinoddevops.online
shipping_host: shipping-"{{ env }}".vinoddevops.online
rabbitmq_host: rabbitmq-"{{ env }}".vinoddevops.online
payment_host: payment-"{{ env }}".vinoddevops.online
app_version: v3