- name: appp setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: javasetup.yaml

- name: copy the {{ component }} service file
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml


- name: install python dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ mysql_host }}"
    login_password: RoboShop@1
    target: "{{ item }}"
  loop: 
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: start and enale shipping module
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes