[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.vinoddevops.online

[redis]
redis-dev.vinoddevops.online

[user]
user-dev.vinoddevops.online

[cart]
cart-dev.vinoddevops.online

[mysql]
mysql-dev.vinoddevops.online

[shipping]
shipping-dev.vinoddevops.online

[rabbitmq]
rabbitmq-dev.vinoddevops.online

[payment]
payment-dev.vinoddevops.online

[frontend]
roboshop-dev.vinoddevops.online